[package]
name = "statusbot"
version = "0.1.0"
authors = ["Kan-Ru Chen <kanru@kanru.info>"]

[dependencies]
futures = "0.1"
hyper = "0.9"
irc = "0.11"
mime = "0.2"
regex = "0.1"
rusqlite = "0.7"
rustc-serialize = "0.3"
time = "0.1"
url = "1.2"
